### ISSUE TITLE
Cuckoo mode as a command-line option

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/viridian_workflow#82]
Not sure if this is done. If so, what is the CLI.

**Comment by jeff-k** [comment]
Cuckoo mode's invocation is documented in the `--help` text for the `cuckoo` task:
```
viridian_workflow cuckoo --help
usage: viridian_workflow <command> <options> cuckoo [-h] --outdir FILENAME [--force] [--keep_bam]
                                                    [--dump_tsv] [--force_amp_scheme STRING]
                                                    [--frs_threshold FLOAT] [--self_qc_depth INT]
                                                    [--max_percent_amps_fail FLOAT]
                                                    [--max_cons_n_percent FLOAT] [--debug] --tech
                                                    {illumina,ont}
                                                    [--built_in_amp_schemes scheme1,scheme2,...]
                                                    [--amp_schemes_tsv FILENAME] [--reads1 FILENAME]
                                                    [--reads2 FILENAME] [--reads FILENAME] --ref_fasta
                                                    FILENAME [--sample_name STRING] --consensus
                                                    FILENAME

optional arguments:
  -h, --help            show this help message and exit
  --outdir FILENAME     REQUIRED. Name of output directory (will be created). This must not exist
                        already, unless the --force option is used to overwrite
  --force               Overwrite output directory, if it already exists. Use with caution!
  --keep_bam            Keep BAM file of reads mapped to reference genome (it is deleted by default)
  --dump_tsv
  --force_amp_scheme STRING
                        Force choice of amplicon scheme. The value provided must exactly match a
                        built-in name or a name in file given by --amp_schemes_tsv
  --frs_threshold FLOAT
                        Masking threshold for consensus base support [0.7]
  --self_qc_depth INT   Masking threshold for consensus base depth [10]
  --max_percent_amps_fail FLOAT
                        Maximum percent of amplicons allowed to fail. The pipeline is stopped as soon
                        as too many failed amplicons are detected [50.0]
  --max_cons_n_percent FLOAT
                        Maximum allowed percentage of Ns in the consensus sequence. The pipeline is
                        stopped as soon as too many Ns are detected [50.0]
  --debug               More verbose logging, and less file cleaning
  --tech {illumina,ont}
                        Sequencing technology, currently supported: illumina,ont
  --built_in_amp_schemes scheme1,scheme2,...
                        Comma-separated list of built in amplicon schemes to use [COVID-
                        AMPLISEQ-V1,COVID-ARTIC-V3,COVID-ARTIC-V4.1,COVID-MIDNIGHT-1200]
  --amp_schemes_tsv FILENAME
                        Tab-delimited file of amplicon schemes to use. Must have header line that
                        includes column names 'Name' and 'File'
  --reads1 FILENAME     Illumina reads file 1
  --reads2 FILENAME     Illumina reads file 2
  --reads FILENAME      Unpaired reads (eg nanopore) file
  --ref_fasta FILENAME  REQUIRED. FASTA file of reference genome
  --sample_name STRING  Name of sample to put in header of final FASTA, VCF, and BAM files [sample]
  --consensus FILENAME
```
`cuckoo` is unlisted in the main help to prevent confusion:
```
viridian_workflow --help
usage: viridian_workflow <command> <options>

viridian_workflow: amplicon-aware consensus maker

optional arguments:
  -h, --help      show this help message and exit
  --version       show program's version number and exit

Available commands:
  
    run_one_sample
                  Run the complete pipeline on one sample
```

**Comment by iqbal-lab** [comment]
So give me an example invocation?

**Comment by jeff-k** [comment]
yes, exactly

```
viridian_workflow cuckoo --dump_tsv --tech illumina --consensus ../covid/dodgy_test.fasta --ref ../covid/MN908947.fasta --outdir /tmp/dodgy_test_ERR7194000/ --reads1 ~/covid/ERR7194000_1.fastq.gz --reads2 ~/covid/ERR7194000_2.fastq.gz
```

**Comment by iqbal-lab** [comment]
does --consensus then have two semantic meanings? If not using consensus, it allows the usert to specify the filename of the consensus, and if using cuckoo mode, it lets you pass in the consensus?

or is it cuckoo specific?

**Comment by martinghunt** [comment]
Bearing in mind we'll be using this in the paper and putting command lines used in methods/suppl, can we please not hide it?

And do we want to rename to something more meaningful to the average user?

**Comment by jeff-k** [comment]
Yes, and it could be difficult to summarise the purpose of it in the `--help` text. I think it's ok to leave the invocation details in the supplementary materials.

**Comment by jeff-k** [comment]
We can open another issue for changing commandline args, I've been pulling in whatever changes you make to them and I'm happy with whatever we go with.

**Comment by martinghunt** [comment]
What's the correct invocation? I can't get it to work (using container built off commit c1b5d6705478ab288c66f80da8bfc2e416fc67fb).

```
$ viridian_workflow cuckoo --dump_tsv --tech illumina --consensus ../gisaid.consensus.fa --ref covid.ref.MN908947.3.fa --outdir OUT --reads1 reads_1.fq.gz --reads2 reads_2.fq.gz
Traceback (most recent call last):
  File "/usr/local/bin/viridian_workflow", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/viridian_workflow/__main__.py", line 201, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/viridian_workflow/tasks/run_one_sample.py", line 9, in cuckoo
    run(options, force_consensus=options.force_consensus)
AttributeError: 'Namespace' object has no attribute 'force_consensus'
```

**Comment by jeff-k** [comment]
It looks like the cuckoo option was broken at some point. The `options.force_consensus` property should have accessed as `options.consensus`
